# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Corina Listaru - Atelier de Zambete 
author: Corina Listaru 
email: corinalistaru71@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  In spatele fiecarui dinte, exista o persoana. Pasiune pentru Zâmbete Impecabile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://corinalistaru.ro"

youtube_username: corinadentatelierdezambete9256
instagram_username: corina.dent
facebook_username: corinadentatelierdezambete

# Build settings
theme: minima

collections_dir: portofoliu 
collections:
    portofoliu:
        output: true

defaults:
  - scope:
      path: ""
      type: "portofoliu"
    values:
      layout: "folio"
